### ISSUE TITLE
add it to npm @types ?

### ISSUE THREAD

**Issue by kunl** [rapropos/typed-markdown-it#3]
I can't find it in 'npm i -D @types/markdown-it' when i use typescript V2.0.3;
can you push it to npm ?

**Comment by rapropos** [comment]
Is there documentation somewhere explaining how to make the required metadata? I haven't come across any yet.

**Comment by fntc** [comment]
Try this one:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by rapropos** [comment]
Added [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13282).

**Comment by rapropos** [comment]
...which was merged.
